### ISSUE TITLE
Is it possible to set poewrline frequency?

### ISSUE THREAD

**Issue by Alvazz** [kcwongjoe/directshow_camera#7]
Thanks for sharing, how to get and set powerline frequency.

**Comment by kcwongjoe** [comment]
It is not supported power line frequency right now. Let me think about it.

**Comment by bugparty** [comment]
the uvc driver did have  support for set powerline frequency, But I am not sure if directshow has an api for it.

**Comment by kcwongjoe** [comment]
Powerline frequency is now supported version 2
