### ISSUE TITLE
Build: default is a restricted keyword

### ISSUE THREAD

**Issue by Riztazz** [kcwongjoe/directshow_camera#9]
both ds_camera_property.h and ds_camera_property.cpp use variable called default which is abuse of C++ language and will result in warning/errors

void importProperty(bool supported, long min, long max, long step, long default, bool isAuto, long value, bool supportAuto, bool supportManual);

and

void DirectShowCameraProperty::importProperty(bool supported, long min, long max, long step, long default, bool isAuto, long value, bool supportAuto, bool supportManual)

**Comment by kcwongjoe** [comment]
Thank you. Have updated it.
